name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - id: find_commit_shas
        uses: nrwl/nx-set-shas@v4

      - name: Lint commit messages
        run: pnpm exec commitlint --from ${{ steps.find_commit_shas.outputs.base }} --to ${{ steps.find_commit_shas.outputs.head }}

      - name: Lint source code
        run: pnpm lint

      - name: Build-time source code type check
        run: pnpm type-check

      - name: Run unit & integration test
        run: pnpm test-run

      - name: Build distribution assets
        run: pnpm build
