name: CI/CD
run-name: ${{github.workflow}} (${{github.event_name}} on ${{ github.ref_name}})

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      do_release:
        type: boolean
        default: false
        description: Do a release
      dry_run:
        type: boolean
        default: false
        description: Do a dry-run of the release

concurrency:
  group: 'cicd'
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: pnpm commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run:
          pnpm commitlint --from ${{ github.event.pull_request.head.sha }}~${{
          github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }}
          --verbose

      - name: Lint source code
        run: pnpm lint

      - name: Build-time source code type check
        run: pnpm type-check

      - name: Run unit & integration test
        run: pnpm test

      - name: Build distribution assets
        run: pnpm build

      - name: Cache build assets
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ github.sha }}

  release:
    if:
      ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.do_release == 'true'  &&
      needs.build.result == 'success'}}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Restore build assets
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name:
          Verify the integrity of provenance attestations and registry signatures for installed
          dependencies
        run: pnpm audit signatures

      - name: Install dependencies
        run: pnpm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm exec semantic-release -d ${{ github.event.inputs.dry_run }}

  sync_readme:
    needs: [release]
    if:
      ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' &&
      needs.release.result == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload README.md to Readme Documentation Environment
        uses: readmeio/rdme@v8
        with:
          rdme: docs ./readme --key=${{ secrets.RDME_API_KEY }} --version=${{ vars.DOCS_VERSION }}

  typedoc:
    needs: [release]
    if:
      ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' &&
      needs.release.result == 'success' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build the TSDoc
        run: pnpm typedoc

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
